Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public string Details { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int EngineerId { get; set; }
    public int MachineId { get; set; }
    public virtual Engineer Engineer { get; set; }
    public virtual Machine Machine { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public virtual DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachine { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public string Details { get; set; }

    public virtual ICollection<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }
    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }


    
    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult DeleteMachine(int joinId, int engineerId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineerId });
    }
    public ActionResult ErrorPage()
    {

      return View();
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Linq;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {

    private readonly FactoryContext _db;

    public HomeController(FactoryContext db)
    {
      _db = db;
    }

    [HttpGet("/")]
    public ActionResult Index()
    {
      ViewBag.Engineers = _db.Engineers.ToList();
      ViewBag.Machines = _db.Machines.ToList();
      return View();
    }

  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a Machine</h2>

<h4>Add a Machine licensed to this Engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new Engineer Profile</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Details)
  @Html.TextBoxFor(model => model.Details)

  <input type="submit" value="Add New Engineer" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Engineers", "Index")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this Engineer?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Details): @Html.DisplayFor(model => model.Details)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This engineer isnt licensed to any machine(s)</p>
}
else
{
  <h4>Machines this Engineer is licensed to do:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Machine.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add a Machine license by this engineer", "AddMachine", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete engineer", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit</h2>

<h4>Edit this Engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Details)
  @Html.EditorFor(model => model.Details)

  <input type="submit" value="Save" />
}
@if (@Model.JoinEntities.Count == 0)
{
  <p>This Engineer isnt licensed to a machine</p>
}
else
{
  <h4>Machines this Engineer is licensed to:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Machine.Name</li>
      @using (Html.BeginForm("DeleteMachine", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        @Html.Hidden("engineerId", @Model.EngineerId)
        <input type="submit" value="Delete this Machine from this Engineer" />
      }
    }
  </ul>
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1>Engineers</h1>

@if (@Model.Count == 0)
{
  <h3>No Engineers have been added yet!</h3>
}

@foreach (Engineer engineer in Model)
{
  <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId }) </li>
}
</br>
<p>@Html.ActionLink("Add a new Engineer", "Create")</p>
<p>@Html.ActionLink("See all Machines", "Index", "Machines")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to Dr. Sillystringz factory!</h1>
<h2>Machines:</h2>
@foreach (var machine in ViewBag.Machines)
{
  <li>@Html.ActionLink($"{machine.Name}", "Details", "Machines", new { id = machine.MachineId }) </li>
}
<h2>Engineers:</h2>
@foreach (var engineer in ViewBag.Engineers)
{
  <li>@Html.ActionLink($"{engineer.Name}", "Details", "Engineers", new { id = engineer.EngineerId }) </li>
}
<p>@Html.ActionLink("Go to Engineers Page", "Index", "Engineers")</p>
<p>@Html.ActionLink("Go to Machines Page", "Index", "Machines")</p>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add an Engineer to a Machine</h2>

<h4>Select an engineer to add to this machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new Machine</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Details)
  @Html.TextBoxFor(model => model.Details)

  <input type="submit" value="Add New Machine" class="btn btn-default" />
}
<p>@Html.ActionLink("Show machines", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Machine Details:</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Details): @Html.DisplayFor(model => model.Details)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This machine does not have any engineers! Add one below.</p>
}
else
{
  <h4>Engineers this Machine is licensed to the following engineer(s):</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Engineer.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add an engineer to this machine", "AddEngineer", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete this machine", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this Machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Details)
  @Html.EditorFor(model => model.Details)

  <input type="submit" value="Save" />
}
@if (@Model.JoinEntities.Count == 0)
{
  <p>This machine doesn't have any engineers!</p>
}
else
{
  <h4>This machine is licensed to the following engineers:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Engineer.Name</li>
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        @Html.Hidden("machineId", @Model.MachineId)
        <input type="submit" value="Delete engineer from this machine" />
      }
    }
  </ul>
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machines:</h1>

@if (@Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
}

@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId }) </li>
}
</br>
<p>@Html.ActionLink("Add a new Machine", "Create")</p>
<p>@Html.ActionLink("See all Engineers", "Index", "Engineers")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Eau Claire's Salon</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @Html.Partial("Footer")
  </body>
</html>